name: Increment Version

on:
  push:
    branches:
      - main  # Or specify the branch you want this to run on
  workflow_dispatch:
    inputs:
      job:
        description: "Select the job to run"
        required: true
        default: "job1"
        type: choice
        options:
          - job1
          - job2

jobs:
  job1:
    if: ${{ github.event.inputs.job == 'job1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run job1
        run: echo "Running job1"

  job2: 
    if: ${{ github.event.inputs.job == 'job2' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run job2
        run: echo "Running job2"

  increment-version:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: ${{ success() && (needs.job1.result == 'success' || needs.job2.result == 'success') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read current version
        id: read_version
        run: |
          # Read the version from version.txt
          VERSION_FILE="version.txt"
          if [[ -f "$VERSION_FILE" ]]; then
            . "$VERSION_FILE"
            echo "Current version is $APP_VERSION"
            echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
            echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          else
            echo "version.txt not found!"
            exit 1
          fi

      - name: Increment version
        id: increment_version
        run: |
          # Split the version into Major, Minor, Patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "${APP_VERSION}"
          
          # Increment Patch by 1
          PATCH=$((PATCH + 1))

          # Check if Patch reached 10
          if [[ "$PATCH" -eq 10 ]]; then
            PATCH=0
            MINOR=$((MINOR + 1))
          fi

          # Check if Minor reached 10
          if [[ "$MINOR" -eq 10 ]]; then
            MINOR=0
            MAJOR=$((MAJOR + 1))
          fi

          # Construct the new version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version is $NEW_VERSION"

          # Update the version file
          echo "APP_NAME=$APP_NAME" > version.txt
          echo "APP_VERSION=$NEW_VERSION" >> version.txt

          # Save NEW_VERSION to an environment file
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and push new version
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
        run: |
          git config user.name "GitHub actions"
          git config user.email "noreply@github.com"
          git add version.txt
          git commit -m "Increment version to $NEW_VERSION"
          git push
